# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e8d6be72dc9ad603a40e5d4c2e9bdf7"
name = "storeInitiatedTransferV2"
handle = "storeinitiatedtransferv2"
application_url = "https://store-initiated-transfer-v2.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_locations, read_inventory, write_inventory_transfers"

[auth]
redirect_urls = ["https://store-initiated-transfer-v2.onrender.com/auth/callback", "https://store-initiated-transfer-v2.onrender.com/auth/shopify/callback", "https://store-initiated-transfer-v2.onrender.com/api/auth/callback"]

[pos]
embedded = true
